Repository ni/labview-icon-editor, pull requests merged in 2025-03, with the labels that each got.

#135 128 replace caraya with lunit
  Tooling/Unit tests/Missing PPLs on LV project.vi
  Tooling/Unit tests/Missing VIs or controls on LV project.vi
  Tooling/Unit tests/Missing classes on LV project.vi
  Tooling/Unit tests/Missing in Project/Get Project MyComputer.vi
  Tooling/Unit tests/Missing in Project/Missing in Project.lvclass
  Tooling/Unit tests/Missing in Project/Test Missing Classes.vi
  Tooling/Unit tests/Missing in Project/Test Missing Libraries.vi
  Tooling/Unit tests/Missing in Project/Test Missing PPLs.vi
  Tooling/Unit tests/Missing in Project/Test Missing VIs.vi
  Tooling/Unit tests/Missing libraries on LV project.vi
  Tooling/Unit tests/Text-Based VI Icon Tests/Test Split Text into Words.vi
  Tooling/Unit tests/Text-Based VI Icon Tests/Text-Based VI Icon Tests.lvclass
  Tooling/Unit tests/Text-Based VI Icon/Split Text into Words.vi
  Tooling/Unit tests/Text-Based VI Icon/Test Caller.vi
  Tooling/Unit tests/Text-Based VI Icon/Text-Based VI Icon Unit Tests.lvlib
  lv_icon_editor.lvproj
  vi.lib/LabVIEW Icon API/Set Text Icon/Text-Based VI Icon.lvlib
Labels: Type: Tooling

#132 90 create a vipc that has fewer dependencies
  README.md
  Tooling/deployment/Dependencies.vipc
  pipeline/scripts/Build.ps1
Labels: Type: Tooling

#143 Feature/25 valid library icon check disable
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/empty_pull_request.md
  .github/workflows/Run unit tests and build.yml
  .github/workflows/trigger-azure-pipeline.yml
  .github/workflows/unit-test-and-build-vi-package.yml
  Tooling/deployment/NI Icon editor.vipb
  Tooling/deployment/VIP_Post-Install Custom Action.vi
  Tooling/deployment/VIP_Pre-Uninstall Custom Action.vi
  pipeline/scripts/Build.ps1
  pipeline/scripts/Cleanup.ps1
  vi.lib/LabVIEW Icon API/Set Text Icon/Qualify Library Icon Core.vi
Labels: Type: Enhancement

#149 Feature/25 valid library icon check disable juan (#130)
  .github/workflows/Run unit tests and build.yml
  .github/workflows/trigger-azure-pipeline.yml
  pipeline/scripts/Build.ps1
Labels: Type: Enhancement

#158 Reusable Release Workflows for the Icon Editor
  .github/workflows/build-vi-package.yml
Labels: minor

#163 Added lv_icon.lvlps to array of directories to be found so that lv_icon.lvlps is included in the delete and archive workflow
  Tooling/support/Get Paths to Icon Editor Files in LV Installation.vi
Labels: patch
